import type { Config } from 'stylelint'

/**
 * CSS property ordering configuration
 */
export const orderConfig: Config = {
  plugins: ['stylelint-order'],
  rules: {
    'order/properties-order': [
      [
        // Positioning
        'position',
        'top',
        'right',
        'bottom',
        'left',
        'z-index',
        // Box Model
        'display',
        'flex',
        'flex-direction',
        'flex-wrap',
        'flex-flow',
        'flex-grow',
        'flex-shrink',
        'flex-basis',
        'justify-content',
        'align-items',
        'align-content',
        'align-self',
        'order',
        'grid',
        'grid-template-rows',
        'grid-template-columns',
        'grid-template-areas',
        'grid-auto-rows',
        'grid-auto-columns',
        'grid-auto-flow',
        'grid-area',
        'grid-row',
        'grid-row-start',
        'grid-row-end',
        'grid-column',
        'grid-column-start',
        'grid-column-end',
        'gap',
        'row-gap',
        'column-gap',
        'float',
        'clear',
        'box-sizing',
        'width',
        'min-width',
        'max-width',
        'height',
        'min-height',
        'max-height',
        'margin',
        'margin-top',
        'margin-right',
        'margin-bottom',
        'margin-left',
        'padding',
        'padding-top',
        'padding-right',
        'padding-bottom',
        'padding-left',
        // Typography
        'font',
        'font-family',
        'font-size',
        'font-weight',
        'font-style',
        'font-variant',
        'font-stretch',
        'line-height',
        'letter-spacing',
        'text-align',
        'text-decoration',
        'text-indent',
        'text-overflow',
        'text-shadow',
        'text-transform',
        'white-space',
        'word-break',
        'word-spacing',
        'word-wrap',
        'color',
        // Visual
        'background',
        'background-color',
        'background-image',
        'background-repeat',
        'background-position',
        'background-size',
        'background-clip',
        'background-origin',
        'background-attachment',
        'border',
        'border-top',
        'border-right',
        'border-bottom',
        'border-left',
        'border-width',
        'border-style',
        'border-color',
        'border-radius',
        'border-top-left-radius',
        'border-top-right-radius',
        'border-bottom-right-radius',
        'border-bottom-left-radius',
        'box-shadow',
        'opacity',
        'filter',
        'backdrop-filter',
        'visibility',
        'cursor',
        // Animation
        'transition',
        'transition-delay',
        'transition-timing-function',
        'transition-duration',
        'transition-property',
        'transform',
        'transform-origin',
        'animation',
        'animation-name',
        'animation-duration',
        'animation-play-state',
        'animation-timing-function',
        'animation-delay',
        'animation-iteration-count',
        'animation-direction',
        // Misc
        'overflow',
        'overflow-x',
        'overflow-y',
        'clip',
        'clip-path',
        'content',
        'quotes',
        'resize',
        'user-select',
        'pointer-events',
        'will-change',
      ],
      {
        type: 'at-rule',
        name: 'include',
      },
      {
        type: 'at-rule',
        name: 'media',
      },
    ],
    'order/properties-alphabetical-order': null,
  },
}
